version: "3.3"

services:

    app-color:
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
            - ./app:/var/www/html/app

        ports:
            - "80:80"
